kind: Deployment
apiVersion: apps/v1
metadata:
  name: bookstore-backend-app
  namespace: bookstore-fb
  labels:
    app.kubernetes.io/name: bookstore-backend-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: bookstore-backend-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bookstore-backend-app
    spec:
     imagePullSecrets:
       - name: awsecr-cred
     initContainers:
       - name: init-mydb
         image: busybox:1.28
         command: ['sh', '-c', "until nslookup mysql-svc.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mydb; sleep 2; done"]
     containers:
       - name: bookstore-backend-app
         image: 303255670930.dkr.ecr.ap-south-1.amazonaws.com/bookstore-backend:fb11
         imagePullPolicy: IfNotPresent
         env:
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: mysql-creds
                key: username
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-creds
                key: password
         ports:
           - containerPort: 8080
         livenessProbe:
           httpGet:
              path: /actuator/health/liveness
              port: 8080
           initialDelaySeconds: 30
           periodSeconds:  45 
           timeoutSeconds:  5
         readinessProbe:
           httpGet:
              path: /actuator/health/readiness
              port: 8080
           initialDelaySeconds: 30
           timeoutSeconds:  5
           periodSeconds: 5
         resources:
            limits: 
              cpu: 400m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 128Mi
         volumeMounts:
         - name: testconfigmap
           mountPath: "/opt/bookstore/application.properties"
           subPath: application.properties
     volumes:
     - name: testconfigmap
       configMap:
         name: bookstore-backend-app
         items:
         - key: application.properties
           path: application.properties
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: bookstore-backend-app
  name: backend-svc
  namespace: bookstore-fb
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 32000	
  selector:
    app.kubernetes.io/name: bookstore-backend-app
  type: NodePort


